version: '3.9'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: stack
    ports:
      - "3307:3306"

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./datalake:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  airflow:
    image: apache/airflow:2.1.1-python3.8
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags/
      - ./airflow/logs:/opt/airflow/logs/
      - ./airflow/plugins:/opt/airflow/plugins/
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password stack --firstname Paulo --lastname Lastname --role Admin --email admin@example.org &&
        airflow scheduler &
        airflow webserver
      "